version: "3.9"

x-redash-service: &redash-service
  build:
    context: .
    target: tests
  volumes:
    - .:/home/tests/app
  env_file:
    - .env

x-tests-environment: &tests-environment
  LOG_LEVEL: "INFO"
  VECTOR_CONFIG_PATH: "/tmp/vector/vector.toml"
  REDIS_URL: "redis://keydb-tests:6379/0"
  RQ_REDIS_URL: "redis://keydb-tests:6379/0"
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres@postgres-tests/tests"
  CSRF_ENFORCED: "false"
  RATELIMIT_ENABLED: "true"
  REDASH_GOOGLE_CLIENT_ID: "dummy"
  REDASH_GOOGLE_CLIENT_SECRET: "dummy"
  MULTI_ORG: "true"

services:
  server-tests:
    <<: *redash-service
    depends_on:
      - clickhouse-tests
      - postgres-tests
      - keydb-tests
    environment:
      <<: *tests-environment
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
      PYTHONUNBUFFERED: 0
    command: tests -x

  keydb-tests:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    restart: unless-stopped

  postgres-tests:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - pgdata15-tests:/var/lib/postgresql/data/pgdata

  clickhouse-tests:
    build:
      context: ./etc/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: test1234
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_INIT_TIMEOUT: 60
    volumes:
      - chdata-tests:/var/lib/clickhouse
    healthcheck:
      test: curl --fail http://localhost:8123
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata15-tests:
  chdata-tests:
