version: "3.9"

x-redash-service: &redash-service
  build:
    context: .
    target: application
  volumes:
    # - .:/home/redash/app
    - vector-etc:/home/redash/etc/vector
  env_file:
    - .env

x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_GUNICORN_TIMEOUT: 60
  VECTOR_CONFIG_PATH: "/home/redash/etc/vector/vector.toml"

services:
  server:
    <<: *redash-service
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
    command: dev_server

  scheduler:
    <<: *redash-service
    depends_on:
      - server
    environment:
      <<: *redash-environment
    command: dev_scheduler

  worker:
    <<: *redash-service
    depends_on:
      - server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
    command: dev_worker

  redis:
    image: redis:6.2.11-alpine
    restart: unless-stopped

  postgres:
    image: postgres:15.2-alpine
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${PGDATA_VOLUME:-pgdata15}:/var/lib/postgresql/data/pgdata

  email:
    image: maildev/maildev
    ports:
      - "1080:80"
    restart: unless-stopped

  vector:
    image: timberio/vector:0.30.X-alpine
    # restart: unless-stopped
    environment:
      VECTOR_WATCH_CONFIG: /etc/vector/vector.toml
    volumes:
      - vector-data:/var/lib/vector
      - vector-etc:/etc/vector:ro
    ports:
      - "8180:8180"
    command: --watch-config

volumes:
  pgdata15:
  vector-data:
  vector-etc:
