version: "3.9"

x-redash-service: &redash-service
  build:
    context: .
    target: development
  volumes:
    - .:/home/redash/app
    - vector-etc:/home/redash/etc/vector
  env_file:
    - .env

x-redash-environment: &redash-environment
  ENVIRONMENT: development
  PYTHONUNBUFFERED: 0
  REDIS_URL: "redis://keydb:6379/0"
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres@postgres/postgres"
  RATELIMIT_ENABLED: "false"
  MAIL_DEFAULT_SENDER: "redash@example.com"
  MAIL_SERVER: "email"
  CSRF_ENFORCED: "true"
  GUNICORN_TIMEOUT: 60
  VECTOR_CONFIG_PATH: "/home/redash/etc/vector/vector.toml"

services:
  server:
    <<: *redash-service
    depends_on:
      - postgres
      - keydb
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5678:5678"
    environment:
      <<: *redash-environment
    command: run_server

  worker:
    <<: *redash-service
    depends_on:
      - server
    environment:
      <<: *redash-environment
      LOG_LEVEL: "INFO"
    command: run_worker

  periodic:
    <<: *redash-service
    depends_on:
      - server
    environment:
      <<: *redash-environment
      LOG_LEVEL: "INFO"
    command: run_periodic

  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    restart: unless-stopped

  postgres:
    image: postgres:15.2-alpine
    ports:
      - "127.0.0.1:15432:5432"
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${PGDATA_VOLUME:-pgdata15}:/var/lib/postgresql/data/pgdata

  email:
    image: maildev/maildev
    ports:
      - "1080:80"
    restart: unless-stopped

  vector:
    image: timberio/vector:0.30.X-alpine
    # restart: unless-stopped
    environment:
      VECTOR_WATCH_CONFIG: /etc/vector/vector.toml
      # VECTOR_LOG: debug
    volumes:
      - vector-data:/var/lib/vector
      - vector-etc:/etc/vector:ro
    ports:
      - "8180:8180"
    command: --watch-config

  clickhouse:
    # restart: unless-stopped
    build:
      context: ./etc/clickhouse
    ports:
      - "127.0.0.1:18123:8123"
      - "127.0.0.1:19000:9000"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - IPC_LOCK
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-default}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_INIT_TIMEOUT: 60
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/val/log/clickhouse-server

volumes:
  clickhouse-data:
  clickhouse-logs:
  pgdata15:
  vector-data:
  vector-etc:
