"""empty message

Revision ID: 48812b497114
Revises: 2e209197905d
Create Date: 2023-05-20 20:01:56.268371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48812b497114'
down_revision = '2e209197905d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_constraint('streams_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('streams_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
